run:
  build-tags:
    - e2e

linters:
  disable-all: true
  enable:
    - goimports
    - gofmt
    - golint
    - govet

linters-settings:
  goimports:
    local-prefixes: github.com/mesosphere/dklb
