:sectnums:
:numbered:
:toc: macro
:toc-title:
:toclevels: 3
:numbered!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Installing `dklb`
:icons: font

[discrete]
== Table of Contents
toc::[]

== Prerequisites

To install `dklb`, the following prerequisites must be met:

* A https://dcos.io/[DC/OS] cluster having https://docs.mesosphere.com/services/edge-lb/[EdgeLB] installed.
** DC/OS must be v1.12.0 or later.
** EdgeLB must be https://github.com/mesosphere/dcos-edge-lb/commit/7f2f353c9368d32f357b505d32104e3e9025721c[`v1.2.3-65-g7f2f353`] or later.
* An https://mesosphere.com/product/kubernetes-engine/[MKE] cluster.
** `kubernetes-cluster` must be https://github.com/mesosphere/dcos-kubernetes-cluster/commit/6dcc522ecad977497cb843a1e3d5c1694e6c070b[`6dcc522`] or later.
** The current kubeconfig context must be configured to point at this cluster.

== Installing

To install `dklb`, the following commands may be run from the root of this repository:

[source,console]
----
$ kubectl create -f docs/deployment/00-prereqs.yaml
$ kubectl create -f docs/deployment/10-deployment.yaml
----

This will create a `dklb` deployment in the `kube-system` namespace having two replicas:

[source,console]
----
$ kubectl -n kube-system get pod --selector "app=dklb"
NAME                    READY   STATUS    RESTARTS   AGE
dklb-756c6c7d88-cgp69   1/1     Running   0          5m45s
dklb-756c6c7d88-slddz   1/1     Running   0          5m45s
----

=== Advanced

==== Disabling automatic registration of the admission webhook

`dklb` includes an https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#admission-webhooks[admission webhook] that validates `Ingress` and `Service` resources annotated for provisioning with EdgeLB.
The admission webhook makes sure that such resources are valid upon creation, and that any subsequent updates that may be performed are valid as well.

`dklb` automatically registers the admission webhook upon starting.
However, and in the unlikely event of it causing problems with `Ingress`/`Service` creation in one's MKE cluster, automatic registration of the admission webhook can be disabled by setting the following feature gate as an argument in `docs/deployment/10-deployment.yaml`:

[source,text]
----
--feature-gates=RegisterAdmissionWebhook=false
----

If `dklb` had already been started without this feature gate, one must manually unregister the admission webhook:

[source,console]
----
$ kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io dklb
mutatingwebhookconfiguration.admissionregistration.k8s.io "dklb" deleted
----

WARNING: Running `dklb` without having registered its admission webhook is **NOT RECOMMENDED**, as it may lead to the creation of invalid `Ingress`/`Service` resources.

== Tailing logs

At any given time, only a single replica is actively working in order to satisfy Ingress/Service resources.
This replica is called the _leader_.
Inspecting the logs of any of the two pods allows for checking which one is the current leader:

[source,console]
----
$ kubectl -n kube-system logs dklb-756c6c7d88-cgp69 | grep leader
time="2018-12-28T16:55:12Z" level=info msg="current leader: dklb-756c6c7d88-slddz"
----

This means that the current leader is the `dklb-756c6c7d88-slddz` pod.
To understand what `dklb` is currently doing, it is necessary to tail the logs of this same pod:

[source,console]
----
$ kubectl -n kube-system logs dklb-756c6c7d88-slddz
time="2018-12-28T16:54:55Z" level=info msg="dklb is starting" version=0ab11a8-dev
time="2018-12-28T16:54:55Z" level=info msg="detected edgelb version: v1.2.3-22-ga35988a"
(...)
time="2018-12-28T16:55:11Z" level=debug msg="starting workers" controller=service-controller
time="2018-12-28T16:55:11Z" level=info msg="started workers" controller=service-controller
time="2018-12-28T16:55:11Z" level=debug msg="starting workers" controller=ingress-controller
time="2018-12-28T16:55:11Z" level=info msg="started workers" controller=ingress-controller
(...)
----

== Uninstalling

To uninstall `dklb`, the following commands may be run from the root of this repository:

[source,console]
----
$ kubectl delete -f docs/deployment/10-deployment.yaml
$ kubectl delete -f docs/deployment/00-prereqs.yaml
----

NOTE: Deleting `dklb` **DOES NOT** delete any EdgeLB pools that may have been created.
