:sectnums:
:numbered:
:toc: macro
:toc-title:
:toclevels: 3
:numbered!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Installing `dklb`
:icons: font

[discrete]
== Table of Contents
toc::[]

== Prerequisites

To install `dklb`, the following prerequisites must be met:

* A https://dcos.io/[DC/OS] cluster having https://docs.mesosphere.com/services/edge-lb/[EdgeLB] installed.
** DC/OS must be v1.12.0 or later.
** EdgeLB must be built and installed from the https://github.com/mesosphere/dcos-edge-lb/tree/master[`master`] branch.
   A stub-universe is available, see https://github.com/mesosphere/dcos-edge-lb#stub-universe[here] for details.
*** EdgeLB https://docs.mesosphere.com/services/edge-lb/1.3/[`v1.3.0`] may be used instead, but some functionality will be missing.
* An https://mesosphere.com/product/kubernetes-engine/[MKE] https://docs.mesosphere.com/services/kubernetes/2.2.0-1.13.3/[`v2.2.0-1.13.3`] (or later) cluster.
** The current kubeconfig context must be configured to point at this cluster.

== Installing

To install `dklb`, the following commands may be run from the root of this repository:

[source,console]
----
$ kubectl create -f docs/deployment/00-prereqs.yaml
$ kubectl create -f docs/deployment/10-deployment.yaml
----

This will create a `dklb` deployment in the `kube-system` namespace having two replicas:

[source,console]
----
$ kubectl -n kube-system get pod --selector "app=dklb"
NAME                    READY   STATUS    RESTARTS   AGE
dklb-756c6c7d88-cgp69   1/1     Running   0          5m45s
dklb-756c6c7d88-slddz   1/1     Running   0          5m45s
----

=== Advanced

==== Customizing the DC/OS service group for EdgeLB pools

By default, EdgeLB pools are created on the `dcos-edgelb/pools` https://docs.mesosphere.com/1.12/security/ent/restrict-service-access/[service group].
In some DC/OS clusters, however, it may be required to customize the service group where EdgeLB pools are created.
This may happen, for example, if EdgeLB itself is installed under a different service group (e.g. `networking/dcos-edgelb`).
In order to achieve this, the following flag must be provided as an argument to `dklb`:

[source,text]
----
--edgelb-pool-group=<edgelb-pool-group>
----

== Tailing logs

At any given time, only a single replica is actively working in order to satisfy Ingress/Service resources.
This replica is called the _leader_.
Inspecting the logs of any of the two pods allows for checking which one is the current leader:

[source,console]
----
$ kubectl -n kube-system logs dklb-756c6c7d88-cgp69 | grep leader
time="2018-12-28T16:55:12Z" level=info msg="current leader: dklb-756c6c7d88-slddz"
----

This means that the current leader is the `dklb-756c6c7d88-slddz` pod.
To understand what `dklb` is currently doing, it is necessary to tail the logs of this same pod:

[source,console]
----
$ kubectl -n kube-system logs dklb-756c6c7d88-slddz
time="2018-12-28T16:54:55Z" level=info msg="dklb is starting" version=0ab11a8-dev
time="2018-12-28T16:54:55Z" level=info msg="detected edgelb version: v1.2.3-22-ga35988a"
(...)
time="2018-12-28T16:55:11Z" level=debug msg="starting workers" controller=service-controller
time="2018-12-28T16:55:11Z" level=info msg="started workers" controller=service-controller
time="2018-12-28T16:55:11Z" level=debug msg="starting workers" controller=ingress-controller
time="2018-12-28T16:55:11Z" level=info msg="started workers" controller=ingress-controller
(...)
----

== Uninstalling

To uninstall `dklb`, the following commands may be run from the root of this repository:

[source,console]
----
$ kubectl delete -f docs/deployment/10-deployment.yaml
$ kubectl delete -f docs/deployment/00-prereqs.yaml
----

Additionally, the admission webhook must be manually unregistered using the following command:

[source,console]
----
$ kubectl delete mutatingwebhookconfiguration dklb
----

NOTE: Deleting `dklb` **DOES NOT** delete any EdgeLB pools that may have been created.
