:sectnums:
:numbered:
:toc: macro
:toc-title:
:toclevels: 3
:numbered!:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Provisioning TCP services with `dklb`
:icons: font

[discrete]
== Table of Contents
toc::[]

== Foreword

`dklb` supports exposing TCP services only.
In particular, exposing UDP or SCTP services is **NOT** supported.

== Instructions

=== Using `dklb` to provision a Kubernetes service

To expose a TCP application running on MKE to either inside or outside the DC/OS cluster, a Kubernetes https://kubernetes.io/docs/concepts/services-networking/service/[`Service`] resource of type https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer[`LoadBalancer`] must be created.
`dklb` will react to this event by provisioning an EdgeLB pool (henceforth referred to as the _target EdgeLB pool_) for the `Service` resource based on its specification.

=== Customizing the name of the EdgeLB pool

By default, `dklb` uses the MKE cluster's name and the `Service` resource's namespace and name to compute the name of the target EdgeLB pool.
To specify a custom name for said EdgeLB pool, one may https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/[annotate] the `Service` resource with the following annotation:

[source,text]
----
kubernetes.dcos.io/edgelb-pool-name: "<edgelb-pool-name>"
----

Depending on whether the "<edgelb-pool-name>" EdgeLB pool exists or not, `dklb` will create or update it in order to expose all ports defined in the `Service` resource.

IMPORTANT: One must not remove or change the value of this annotation at any time after it is added to a given `Service` resource.

=== Intra-DC/OS vs external exposure

By default, `dklb` exposes services to _outside_ the DC/OS cluster by requesting for the target EdgeLB pool to be scheduled onto a https://docs.mesosphere.com/1.12/overview/architecture/node-types/#public-agent-nodes[public DC/OS agent].
However, and in order to accommodate all possible needs, `dklb` supports explicitly specifying a http://mesos.apache.org/documentation/latest/roles/[Mesos role] for the target EdgeLB pool:

[source,text]
----
kubernetes.dcos.io/edgelb-pool-role: "<edgelb-pool-role>"
----

In particular, to expose a service to _inside_ DC/OS only, `*` should be used as the value of `<edgelb-pool-role>`.
Providing said value will cause `dklb` to request for the target EdgeLB pool to be scheduled onto a https://docs.mesosphere.com/1.12/overview/architecture/node-types/#private-agent-nodes[private DC/OS agent].

[WARNING]
====
The value of this annotation is observed only when the target EdgeLB pool is created.

In other words, changing the value of this annotation after the target EdgeLB pool has been created and provisioned will produce no effect.
====

=== Customizing the exposed ports

`dklb` provisions the target EdgeLB pool by looking at the service's ports and creating an EdgeLB https://docs.mesosphere.com/services/edge-lb/1.2/pool-configuration/v2-reference/[backend] and an EdgeLB https://docs.mesosphere.com/services/edge-lb/1.2/pool-configuration/v2-reference/[frontend] per port.
By default, `dklb` uses the port number that is defined on the `Service` resource as the frontend's bind port.
In some situations, however, using a different port number as the frontend's bind port may be required.footnote:[This may happen, for example, in scenarios where there are "port clashes" between services in the same or different MKE clusters.]
In order to accommodate more advanced use cases, `dklb` supports defining custom port mappings via annotations of the following form:

[source,text]
----
kubernetes.dcos.io/edgelb-pool-portmap.<service-port>: "<frontend-bind-port>"
----

When such an annotation is provided, `dklb` will use `<frontend-bind-port>` instead of `<service-port>` as the actual frontend bind port.

[WARNING]
====
Changing the value of this annotation after the `Service` resource is created is supported, but may cause disruption (as the target EdgeLB pool will most likely be re-deployed).

One should plan port mappings ahead whenever possible in order to prevent changes from being required in the first place.
====

=== Customizing the target EdgeLB pool

`dklb` supports customizing CPU, memory and size requests for the target EdgeLB pool.
Custom values for these requests can be specified using the following annotations:

[source,text]
----
kubernetes.dcos.io/edgelb-pool-cpus: "<edgelb-pool-cpus>"
kubernetes.dcos.io/edgelb-pool-mem: "<edgelb-pool-mem>"
kubernetes.dcos.io/edgelb-pool-size: "<edgelb-pool-size>"
----

The values of `<edgelb-pool-cpus>` and `<edgelb-pool-mem>` must obey the same format as https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/[container resource requests and limits] (e.g. `200m` for 0.2 CPU and `32Mi` for 32MiB RAM).
The value of `<edgelb-pool-size>` must be a positive integer.

[WARNING]
====
The value of these annotations are observed only when the target EdgeLB pool is created.

In other words, changing the value of any of these annotations after the target EdgeLB pool has been created and provisioned will produce no effect.
====

=== Advanced topics

==== Customizing the DC/OS virtual network to join

By design, pools exposing Kubernetes services to _outside_ the DC/OS cluster (i.e. pools using the `slave_public` role) will run atop the DC/OS agents' host network.

Also by design, pools exposing Kubernetes services to _inside_ the DC/OS cluster will run atop the https://docs.mesosphere.com/1.12/networking/SDN/dcos-overlay/[`dcos` virtual network].
It is, however, possible to override this and pick any https://docs.mesosphere.com/1.12/networking/SDN/usage/ [custom DC/OS virtual network] for these pools, by providing the following annotation:

[source,text]
----
kubernetes.dcos.io/edgelb-pool-network: "<edgelb-pool-network>"
----

[WARNING]
====
The value of this annotation is observed only when the target EdgeLB pool is created and the pool role is not `slave_public` (the default).

In other words, changing the value of this annotation after the target EdgeLB pool has been created and provisioned will produce no effect.
====

==== Using a pre-existing pool to expose a Kubernetes service

In certain scenarios, it may be desirable to use a pre-existing EdgeLB pool to expose a Kubernetes service (instead of having `dklb` creating one).
This can easily be achieved by providing the name of the pre-existing EdgeLB pool as the value of the `kubernetes.dcos.io/edgelb-pool-name` annotation.

==== Sharing an EdgeLB pool between Kubernetes services

To share an EdgeLB pool between two or more Kubernetes services, it is enough to provide the name of said pool as the value of `kubernetes.dcos.io/edgelb-pool-name` annotation in all of the corresponding `Service` resources.
When an EdgeLB pool is shared between two or more Kubernetes services, the following aspects should be taken into consideration:

* Each remaining `kubernetes.dcos.io/edgelb-*` annotation must have the exact same value across all `Service` resources sharing an EdgeLB pool.
* Sharing an EdgeLB pool between services in different MKE clusters is allowed, but should be avoided whenever possible.
* Changing or deleting one of the `Service` resources exposed on a shared EdgeLB pool may cause disruption in all applications exposed on said EdgeLB pool.

== Example

=== Exposing a Redis instance

This example illustrates how to expose a Redis instance to outside the DC/OS cluster.
To start with, a simple `redis` pod will be created:

[source,console]
----
$ cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redis
spec:
  containers:
  - name: redis
    image: redis:5.0.3
    ports:
    - name: redis
      containerPort: 6379
      protocol: TCP
EOF
pod/redis created
----
[source,console]
----
$ kubectl get pod --selector "app=redis"
NAME    READY   STATUS    RESTARTS   AGE
redis   1/1     Running   0          100s
----

Then, a `Service` resource of type `LoadBalancer` targeting the specified pod will also be created:

[source,console]
----
$ cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.dcos.io/edgelb-pool-name: "dklb-redis"
    kubernetes.dcos.io/edgelb-pool-portmap.6379: "16379"
  labels:
    app: redis
  name: redis
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
EOF
service/redis created
----
[source,console]
----
$ kubectl get svc --selector "app=redis"
NAME    TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
redis   LoadBalancer   10.100.80.96   <pending>     6379:32213/TCP   2m42s
----

The annotations defined on this `Service` resource will cause `dklb` to expose the service using an EdgeLB pool called `dklb-redis`, mapping the service's `6379` port to the EdgeLB pool's `16379` port.
At this point, querying the EdgeLB API should confirm the existence of a pool called `dklb-redis` exposing said port:

[source,console]
----
$ dcos edgelb list
  NAME        APIVERSION  COUNT  ROLE          PORTS
  dklb-redis  V2          1      slave_public  9090, 16379
----

This means that `dklb` has successfully created and provisioned the target EdgeLB pool based on the spec of the `redis` service.

=== Connecting to the Redis instance

As of this writing, `dklb` is still unable to report the IP(s)/name(s) at which the service is exposed.
Hence, at this point and in order to test connectivity, it is necessary to manually check which public DC/OS agent the target EdgeLB pool was scheduled onto.
Assuming this IP is `<public-dcos-agent-ip>`, `telnet` may be used to confirm that the Redis instance is correctly exposed to outside the DC/OS cluster:

[source,console]
----
$ telnet <public-dcos-agent-ip> 16379
Trying <public-dcos-agent-ip>...
Connected to <public-dcos-agent-ip>.
Escape character is '^]'.
----

WARNING: Depending on the firewall rules in place for the DC/OS cluster, it may be necessary to manually allow traffic to port `16379` in order to allow connectivity.

This means that the Redis instance is indeed reachable at `<public-dcos-agent-ip>:16379` (i.e., from outside the DC/OS cluster).
Additional commands may be run inside `telnet` in order to verify that everything is working as expected:

[source,console]
----
$ telnet <public-dcos-agent-ip> 16379
(...)
SET foo bar
+OK
GET foo
$3
bar
QUIT
+OK
Connection closed by foreign host.
----

=== Cleaning up

After testing finishes, cleanup of the Kubernetes service and of the target EdgeLB pool can be done by running the following commands:

[source,console]
----
$ kubectl delete svc redis
$ kubectl delete pod redis
----

The `dklb-redis` EdgeLB pool will be automatically deleted.
